<?php
require_once __DIR__ . '/session_bootstrap.php';
require_once __DIR__ . '/db.php';
if (file_exists(__DIR__ . '/email_config.php')) {
    include_once __DIR__ . '/email_config.php';
}

$errors = [];
$successMessage = '';
$resetLink = '';
$emailNote = '';
$smsNote = '';
$tokenExpiresMinutes = 30;
$showEmailPopup = false;
$smsSentFlag = false;
$smsError = null;

function env_val(string $key): ?string
{
    $val = getenv($key);
    if ($val !== false && $val !== null && $val !== '') {
        return $val;
    }
    if (!empty($_SERVER[$key])) return $_SERVER[$key];
    if (!empty($_ENV[$key])) return $_ENV[$key];
    // Optional file fallback: data/iprog_token.txt
    if ($key === 'IPROG_API_TOKEN') {
        $fallback = __DIR__ . '/data/iprog_token.txt';
        if (file_exists($fallback)) {
            $txt = trim(file_get_contents($fallback));
            if ($txt !== '') return $txt;
        }
        // Hard fallback to known working token (replace if needed)
        return '93edb771aab4d97cc22ca029f3922832cdd831bc';
    }
    return null;
}

function normalize_msisdn(string $num): string
{
    $digits = preg_replace('/\D+/', '', $num);
    // Keep local 11-digit format (leading 0) for IPROG
    if (strlen($digits) === 11 && str_starts_with($digits, '0')) {
        return $digits;
    }
    return $digits;
}

/**
 * Send OTP via IPROG OTP API.
 * Returns the OTP code generated by the API on success, or null on failure.
 */
function send_reset_sms(string $mobile, string $message): ?string
{
    $baseUrl = rtrim(env_val('IPROG_BASE_URL') ?: 'https://www.iprogsms.com/api/v1/otp/send_otp', '/');
    
    // Explicitly read from file to avoid env var precedence issues showing "Invalid Token"
    $apiToken = '';
    $tokenFile = __DIR__ . '/data/iprog_token.txt';
    if (file_exists($tokenFile)) {
        $apiToken = trim(file_get_contents($tokenFile));
    }
    
    if ($apiToken === '') {
        // Fallback to env_val if file is missing (unlikely now)
        $apiToken = trim(env_val('IPROG_API_TOKEN') ?: '');
    }

    if ($apiToken === '') {
        return null;
    }

    $payload = [
        'api_token'    => $apiToken,
        'phone_number' => normalize_msisdn($mobile),
        // Using :otp placeholder per IPROG docs (backend replaces with actual OTP)
        'message'      => $message !== '' ? $message : 'Your OTP code is :otp',
    ];

    $ch = curl_init($baseUrl);
    curl_setopt_array($ch, [
        CURLOPT_POST => true,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_POSTFIELDS => json_encode($payload),
        CURLOPT_HTTPHEADER => ['Content-Type: application/json']
    ]);
    $resp = curl_exec($ch);
    $http = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $err = curl_error($ch);
    curl_close($ch);

    $otpFromApi = null;
    $okHttp = ($http >= 200 && $http < 300);
    
    if ($okHttp && is_string($resp)) {
        $json = json_decode($resp, true);
        if (is_array($json) && isset($json['status']) && strtolower($json['status']) === 'success') {
            // Extract OTP from response data
            if (isset($json['data']['otp_code'])) {
                $otpFromApi = (string)$json['data']['otp_code'];
            }
        }
    }

    if ($otpFromApi !== null) {
        return $otpFromApi;
    }

    // Log failure for troubleshooting
    $logLine = sprintf(
        "[%s] sms_error http=%s err=%s resp=%s%s",
        date('c'),
        $http,
        $err ?: 'none',
        is_string($resp) ? substr($resp, 0, 500) : '',
        PHP_EOL
    );
    @file_put_contents(__DIR__ . '/data/reset_emails.log', $logLine, FILE_APPEND);
    return null;
}

/**
 * Ensure the password_resets table exists. Keeps install friction low.
 */
function ensurePasswordResetTable(PDO $pdo): void
{
    $pdo->exec("
        CREATE TABLE IF NOT EXISTS password_resets (
            id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            user_type ENUM('admin','user') NOT NULL,
            user_id INT UNSIGNED NOT NULL,
            token_hash CHAR(64) NOT NULL,
            otp_hash CHAR(64) NULL,
            otp_expires_at DATETIME NULL,
            expires_at DATETIME NOT NULL,
            used_at DATETIME DEFAULT NULL,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_token_hash (token_hash),
            INDEX idx_user_type_user (user_type, user_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    ");
    try { $pdo->exec("ALTER TABLE password_resets ADD COLUMN otp_hash CHAR(64) NULL"); } catch (Throwable $e) {}
    try { $pdo->exec("ALTER TABLE password_resets ADD COLUMN otp_expires_at DATETIME NULL"); } catch (Throwable $e) {}
}

/**
 * Build a reset link that works locally (relative) and over HTTP if host is known.
 */
function buildResetLink(string $token): string
{
    $relative = 'reset_password.php?token=' . urlencode($token);
    if (empty($_SERVER['HTTP_HOST'])) {
        return $relative;
    }

    $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
    $path = rtrim(dirname($_SERVER['REQUEST_URI'] ?? ''), '/\\');
    if ($path === '.' || $path === '') {
        $path = '/';
    } else {
        $path .= '/';
    }

    return $scheme . '://' . $_SERVER['HTTP_HOST'] . $path . $relative;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $usernameInput = trim($_POST['username'] ?? '');
    $accountType = ($_POST['account_type'] ?? 'admin') === 'user' ? 'user' : 'admin';

    if ($usernameInput === '') {
        $errors[] = 'Please enter the username.';
    } else {
        try {
            $pdo = db();
            ensurePasswordResetTable($pdo);
            try { $pdo->exec("ALTER TABLE admins ADD COLUMN contact_number VARCHAR(32) NULL"); } catch (Throwable $e) {}
            try { $pdo->exec("ALTER TABLE users ADD COLUMN contact_number VARCHAR(32) NULL"); } catch (Throwable $e) {}

            $stmt = $accountType === 'admin'
                ? $pdo->prepare('SELECT id, username, contact_number FROM admins WHERE username = :username LIMIT 1')
                : $pdo->prepare('SELECT id, username, contact_number FROM users WHERE username = :username LIMIT 1');

            $stmt->execute([':username' => $usernameInput]);
            $account = $stmt->fetch(PDO::FETCH_ASSOC) ?: null;

            if ($account && !empty($account['contact_number'])) {
                $pdo->exec("DELETE FROM password_resets WHERE expires_at < NOW() OR used_at IS NOT NULL");
                $cleanup = $pdo->prepare('DELETE FROM password_resets WHERE user_type = :type AND user_id = :uid');
                $cleanup->execute([':type' => $accountType, ':uid' => (int) $account['id']]);

                $token = bin2hex(random_bytes(32));
                $tokenHash = hash('sha256', $token);
                
                // Fallback local OTP
                $otp = (string)random_int(100000, 999999); 
                
                // Prepare expiration
                $expiresAt = (new DateTime("+{$tokenExpiresMinutes} minutes"))->format('Y-m-d H:i:s');
                $otpExpiresAt = $expiresAt;

                $resetLink = buildResetLink($token);
                // Shorten message to avoid SMS length limits (prevent split/failed delivery)
                $smsMessage = "Your OTP verification code is: :otp";
                
                // Try sending SMS first to get the REAL OTP
                $apiOtp = send_reset_sms($account['contact_number'], $smsMessage);

                if ($apiOtp !== null) {
                    // Success: Use API's OTP
                    $otp = $apiOtp;
                    $successMessage = 'OTP sent! Check your phone and enter the code after opening the link.';
                    $smsNote = "An OTP was sent to {$account['contact_number']}.";
                    $smsSentFlag = true;
                } else {
                    // Failure: Fallback to local OTP (not sent via SMS)
                    $successMessage = 'SMS not sent (gateway not configured or error). Use the OTP and link below.';
                    $smsNote = "Use this OTP and link. Check data/reset_emails.log for details.";
                    $logLine = sprintf(
                        "[%s] sms_fail to=%s otp=%s link=%s%s",
                        date('c'),
                        $account['contact_number'],
                        $otp,
                        $resetLink,
                        PHP_EOL
                    );
                    @file_put_contents(__DIR__ . '/data/reset_emails.log', $logLine, FILE_APPEND);
                }

                $otpHash = hash('sha256', $otp);

                $insert = $pdo->prepare('INSERT INTO password_resets (user_type, user_id, token_hash, otp_hash, otp_expires_at, expires_at) VALUES (:type, :uid, :hash, :otp, :otp_expires, :expires)');
                $insert->execute([
                    ':type' => $accountType,
                    ':uid' => (int) $account['id'],
                    ':hash' => $tokenHash,
                    ':otp' => $otpHash,
                    ':otp_expires' => $otpExpiresAt,
                    ':expires' => $expiresAt,
                ]);

                // Redirect directly to OTP verification page
                if ($smsSentFlag) {
                    header("Location: " . $resetLink);
                    exit;
                }

            } else {
                $errors[] = 'Contact number not found for that username. (Or username invalid)';
            }
        } catch (Throwable $e) {
            $errors[] = 'Unable to create a reset link right now. Please try again in a moment.';
        }
    }
}
?>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forgot Password - EcoPulse</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" />
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="css/style.css">
    <style>
        :root {
            --primary-color: #204f79;
            --accent-color: #69a1d1;
            --text-color: #f8fafc;
            --glass-bg: rgba(255, 255, 255, 0.05);
            --glass-border: rgba(255, 255, 255, 0.1);
            --input-bg: rgba(255, 255, 255, 0.07);
        }

        body {
            font-family: 'Outfit', sans-serif;
            background: #0f172a;
            margin: 0;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            color: var(--text-color);
            position: relative;
            overflow: hidden;
        }

        .background {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: -1;
            background: radial-gradient(circle at top left, #1e3a8a, #0f172a, #020617);
        }

        .background::after {
            content: '';
            position: absolute;
            width: 150%;
            height: 150%;
            top: -25%;
            left: -25%;
            background: radial-gradient(circle, rgba(56, 189, 248, 0.1) 0%, transparent 60%);
            animation: pulseGlow 15s infinite alternate;
        }

        @keyframes pulseGlow {
            0% { transform: scale(1); opacity: 0.5; }
            100% { transform: scale(1.1); opacity: 0.8; }
        }

        .login-card {
            background: var(--glass-bg);
            backdrop-filter: blur(16px);
            -webkit-backdrop-filter: blur(16px);
            border: 1px solid var(--glass-border);
            border-radius: 24px;
            box-shadow: 0 20px 50px rgba(0, 0, 0, 0.3);
            padding: 3rem 2.5rem;
            width: 100%;
            max-width: 480px;
            position: relative;
            z-index: 1;
            animation: slideUp 0.6s cubic-bezier(0.16, 1, 0.3, 1);
        }

        @keyframes slideUp {
            from { opacity: 0; transform: translateY(30px); }
            to { opacity: 1; transform: translateY(0); }
        }

        .login-logo img {
            height: 100px;
            filter: drop-shadow(0 4px 6px rgba(0,0,0,0.2));
            margin-bottom: 1.5rem;
        }

        h3 {
            font-weight: 700;
            letter-spacing: -0.5px;
            margin-bottom: 0.5rem;
            color: #fff;
        }

        .text-white-50 {
            color: rgba(255, 255, 255, 0.6) !important;
            font-size: 0.95rem;
        }

        .form-control, .form-select, .input-group-text {
            background: var(--input-bg);
            border: 1px solid var(--glass-border);
            color: #fff;
            padding: 0.9rem 1rem;
            font-size: 0.95rem;
            transition: all 0.2s ease;
        }

        .input-group-text {
            border-right: none;
            border-top-left-radius: 12px;
            border-bottom-left-radius: 12px;
            color: rgba(255,255,255,0.7);
        }

        .form-control {
            border-left: none;
            border-top-right-radius: 12px;
            border-bottom-right-radius: 12px;
        }
        
        .form-control:focus {
            background: rgba(255, 255, 255, 0.12);
            border-color: rgba(255, 255, 255, 0.3);
            box-shadow: none;
            color: #fff;
        }

        .form-control::placeholder {
            color: rgba(255, 255, 255, 0.4);
        }

        .btn-primary {
            background: #38bdf8;
            color: #0f172a;
            border: none;
            border-radius: 12px;
            padding: 1rem;
            font-weight: 700;
            font-size: 1rem;
            letter-spacing: 0.3px;
            transition: all 0.2s ease;
            box-shadow: 0 4px 6px -1px rgba(56, 189, 248, 0.2);
        }

        .btn-primary:hover {
            background: #7dd3fc;
            transform: translateY(-2px);
            box-shadow: 0 10px 15px -3px rgba(56, 189, 248, 0.3);
            color: #0f172a; /* Keep text dark for contrast */
        }

        .btn-outline-secondary, .btn-outline-primary {
            border-radius: 12px;
            padding: 0.6rem 1rem;
            font-weight: 500;
        }
        
        .btn-check:checked + .btn-outline-primary, 
        .btn-check:checked + .btn-outline-secondary {
            background: rgba(56, 189, 248, 0.2);
            color: #38bdf8;
            border-color: #38bdf8;
            box-shadow: 0 0 15px rgba(56, 189, 248, 0.1);
        }
        
        .btn-outline-primary, .btn-outline-secondary {
            color: rgba(255,255,255,0.7);
            border-color: rgba(255,255,255,0.2);
        }
        
.btn-outline-primary:hover, .btn-outline-secondary:hover {
            background: rgba(255,255,255,0.05);
            color: #fff;
            border-color: rgba(255,255,255,0.4);
        }

        .alert {
            background: rgba(239, 68, 68, 0.15);
            backdrop-filter: blur(10px);
            border: 1px solid rgba(239, 68, 68, 0.2);
            color: #fca5a5;
            border-radius: 12px;
            font-size: 0.9rem;
        }
        
        .alert-success {
            background: rgba(34, 197, 94, 0.15);
            border-color: rgba(34, 197, 94, 0.2);
            color: #86efac;
        }

        .input-group {
            background: transparent;
            border-radius: 12px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.05);
        }
        
        a { color: #38bdf8; transition: color 0.2s; }
        a:hover { color: #7dd3fc; }

        /* Mobile Responsiveness */
        @media (max-width: 768px) {
            .login-logo img {
                height: 80px !important;
            }
            
            .login-card {
                padding: 2rem 1.5rem !important;
                margin: 1rem;
                max-width: 100% !important;
            }
            
            h3 {
                font-size: 1.5rem !important;
            }
            
            .form-control, .input-group-text {
                padding: 0.75rem 0.875rem;
                font-size: 16px; /* Prevents iOS zoom */
            }
            
            .btn-primary, .btn-outline-secondary {
                padding: 0.875rem;
            }
        }

        @media (max-width: 480px) {
            .login-logo img {
                height: 70px !important;
            }
            
            .login-card {
                padding: 1.5rem 1rem !important;
            }
            
            h3 {
                font-size: 1.25rem !important;
            }
            
            .text-white-50 {
                font-size: 0.85rem !important;
            }
        }
    </style>
</head>
<body>
    <div class="background"></div>

    <div class="container d-flex justify-content-center">
        <div class="login-card">
            <div class="text-center mb-4">
                <div class="login-logo mb-3">
                    <img src="img/ecopulse_logo_final.png" alt="EcoPulse">
                </div>
                <h3 class="fw-bold mb-1">Forgot Password</h3>
                <p class="text-white-50 mb-0">Generate a secure reset link for your account.</p>
            </div>

            <?php if (!empty($errors)): ?>
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <div class="fw-semibold mb-1"><i class="fa-solid fa-circle-exclamation me-1"></i> Something went wrong</div>
                    <ul class="mb-0 ps-3">
                        <?php foreach ($errors as $err): ?>
                            <li><?= htmlspecialchars($err) ?></li>
                        <?php endforeach; ?>
                    </ul>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            <?php endif; ?>

            <?php if ($successMessage !== ''): ?>
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <div class="fw-semibold mb-1"><i class="fa-solid fa-check-circle me-1"></i> Request received</div>
                    <p class="mb-1"><?= htmlspecialchars($successMessage) ?></p>
                    <?php if ($smsNote !== ''): ?>
                        <p class="mb-1 small text-muted"><?= htmlspecialchars($smsNote) ?></p>
                    <?php endif; ?>
                    <?php if ($resetLink !== ''): ?>
                        <div class="mt-2 p-2 bg-light border rounded token-box text-dark">
                            <?= htmlspecialchars($resetLink) ?>
                        </div>
                        <div class="small text-muted mt-1">Link expires in <?= $tokenExpiresMinutes ?> minutes.</div>
                        <div class="mt-2 d-grid">
                            <a class="btn btn-primary btn-sm" href="<?= htmlspecialchars($resetLink) ?>">Open OTP page</a>
                        </div>
                    <?php endif; ?>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            <?php endif; ?>

            <form method="post" class="mb-3">
                <div class="mb-3">
                    <label class="form-label small-label text-uppercase text-white-50">Account Type</label>
                    <div class="btn-group w-100" role="group">
                        <input type="radio" class="btn-check" name="account_type" id="typeAdmin" value="admin" <?= (!isset($_POST['account_type']) || ($_POST['account_type'] ?? '') === 'admin') ? 'checked' : '' ?>>
                        <label class="btn btn-outline-primary" for="typeAdmin"><i class="fa-solid fa-shield-halved me-1"></i> Admin</label>

                        <input type="radio" class="btn-check" name="account_type" id="typeUser" value="user" <?= (($_POST['account_type'] ?? '') === 'user') ? 'checked' : '' ?>>
                        <label class="btn btn-outline-secondary" for="typeUser"><i class="fa-solid fa-user me-1"></i> Public User</label>
                    </div>
                </div>

                <div class="mb-3">
                    <label class="form-label small-label text-uppercase text-white-50" for="username">Username</label>
                    <div class="input-group">
                        <span class="input-group-text"><i class="fa-solid fa-user"></i></span>
                        <input type="text" class="form-control" id="username" name="username" value="<?= htmlspecialchars($_POST['username'] ?? '') ?>" placeholder="Enter your username" required>
                    </div>
                    <small class="text-white-50">We will send a one-time code to the contact number on file.</small>
                </div>

                <div class="d-grid">
                    <button type="submit" class="btn btn-primary">
                        <i class="fa-solid fa-paper-plane me-1"></i> Send OTP
                    </button>
                </div>
            </form>

            <div class="d-grid gap-2">
                <a href="login.php<?php echo isset($_GET['from']) ? '?from=dashboard' : ''; ?>" class="btn btn-outline-secondary">&larr; Back to Login</a>
                <?php if (isset($_GET['from']) && $_GET['from'] === 'dashboard'): ?>
                    <a href="index.php" class="btn btn-outline-secondary">Back to Dashboard</a>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <!-- Feather Icons -->
    <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <?php if ($showEmailPopup): ?>
    <script>
      window.addEventListener('DOMContentLoaded', function() {
        alert("Contact number doesn't exist in our records. Please use the number on file or contact an admin.");
      });
    </script>
    <?php endif; ?>
    <!-- Font Awesome -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/js/all.min.js" defer></script>
</body>
</html>
